# Generated by Django 3.1.1 on 2020-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('pod_type', models.CharField(choices=[('S', 'Small Coffee Pod'), ('L', 'Large Coffee Pod'), ('E', 'Espresso Pod')], default='S', max_length=1)),
                ('flavors', models.CharField(choices=[('VAN', 'VAN'), ('CAR', 'CAR'), ('PSL', 'PSL'), ('MOC', 'MOC'), ('HAZ', 'HAZ')], default='VAN', max_length=3)),
                ('pack_size', models.CharField(choices=[('1', '1'), ('36', '36'), ('60', '60'), ('84', '84')], default='1', max_length=2)),
            ],
        ),
    ]
